# Doctrine Configuration
doctrine:
    dbal:
        driver:         pdo_mysql
        host:           "%database_host%"
        port:           "%database_port%"
        dbname:         "%database_name%"
        user:           "%database_user%"
        password:       "%database_password%"
        server_version: "%database_server_version%"
        charset:  UTF8
        mapping_types:
            enum: string
        types:
            SightTicketType: AppBundle\DBAL\Types\SightTicketType
            FriendStatusType: AppBundle\DBAL\Types\FriendStatusType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
