vich_uploader:
    db_driver: orm

    mappings:
        sight_image:
            uri_prefix:         /images/sights
            upload_destination: "%kernel.root_dir%/../web/images/sights"
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
